### ISSUE TITLE
cfstore plugin requirements

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/recsync#1]
We have been working on developing a plugin for recsync which pipes the data to channelfinder.

Currently the features supported are 
1. which ioc startup, all the records are added to channelfinder along with properties iocName, hostName, time, and ovStatus
2. upon ioc reboot, the "time" 

Missing
When an IOC shuts down the information available in the transaction object consists of only the host ip (as part of the TR.src). Since there might be more than one ioc running on a particular host, the IOCNAME information is necessary to update channelfinder correctly.

**Comment by mdavidsaver** [comment]
> When an IOC shuts down the information available in the transaction object consists of only the host ip

Both IP address and port number are included, which together are unique.

**Comment by shroffk** [comment]
Currently cfstore dose not record the port, instead it uses the iocname+hostname.
Maybe the port should be stored as a property too.

**Comment by mdavidsaver** [comment]
Keeping "ip:port" seems reasonable
