### ISSUE TITLE
recsync fails to correctly identify different iocs

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/recsync#10]
As reported by ESS in certain situations the TR object src information seems to be the same for different ioc. The problem was noticed when cfstore properties were not correctly updated with ioc boots.

**Comment by mdavidsaver** [comment]
This was a stupid on my part.  Was calling 'getHost()' instead of 'getPeer()'.  Should be fixed by 66cf9c108bfc620f367deabacebb62bb6494e256

**Comment by shroffk** [comment]
Yes, this fixed the issue
