### ISSUE TITLE
Issue deploying mulitple recceiver instances

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/recsync#74]
When deploying multiple recceivers pushing to one channel finder instance, there is an issue with the clean_service method where it will set all pvStatus properties on all PVs in CF to "Inactive" on recceiver startup. This works fine if you have one recceiver but once there are more, as you start each recceiver then it will mark all the PVs belonging to the other recceiver instances "Inactive"

Setting the cleanOnStart/cleanOnStop preference setting stops the clean_service method from getting called but I think you then lose some functionality. Updating the CF query in clean_service with a preference setting to allow you to limit the scope of the clean could be useful but not sure how to limit it. Query on iocid since usually it's a per subnet basis for each instance? 

https://github.com/ChannelFinder/recsync/blob/master/server/recceiver/cfstore.py#L284

**Comment by shroffk** [comment]
I agree.. I think that might be the issue.

**Comment by tynanford** [comment]
fixed via https://github.com/ChannelFinder/recsync/pull/78 , thanks @jacomago !
