### ISSUE TITLE
Recceiver ignores logging level in conf file

### ISSUE THREAD

**Issue by tynanford** [ChannelFinder/recsync#96]
It seems that since the move to twisted logging framework here https://github.com/ChannelFinder/recsync/pull/83 , I can't set the logging level with `loglevel` in the conf file. Has anyone else come across this?

For me the logs always are showing everything (debug, info, warn, etc.)

**Comment by tynanford** [comment]
@jacomago have you noticed the same issue at ESS?

**Comment by jacomago** [comment]
We aren't running with later than 1.6. But I can still see the logLevel isn't working anymore in my docker test setup.

**Comment by tynanford** [comment]
closed via https://github.com/ChannelFinder/recsync/pull/97
